### ISSUE TITLE
Update guide mentioning default skeleton

### ISSUE THREAD

**Issue by 3cp** [aurelia/aurelia.github.io#12]
The default skeleton created by `npx makes aurelia` has been migrated from webpack to vite.
There are few doc parts needs to update to reflect that.

**Comment by 3cp** [comment]
@Vheissu I have no permission to edit assignees.

**Comment by Vheissu** [comment]
@3cp I've updated the docs account for Vite as default and updated Shadow DOM and CSS Modules doc parts.
