### ISSUE TITLE
Header menus don’t work on tablets

### ISSUE THREAD

**Issue by lancelot316** [aurelia/aurelia.github.io#15]
There is no way to trigger the docs, ecosystem, and about menus when viewing the site on a tablet

Device: iPad Pro 11-inch

![IMG_0749](https://github.com/user-attachments/assets/33f483f7-2aa6-4cc2-bc7d-d742bb39fa37)

**Comment by Vheissu** [comment]
All fixed. Thanks for letting us know @lancelot316
