### ISSUE TITLE
Add a comment section

### ISSUE THREAD

**Issue by avrahamcool** [aurelia/aurelia.github.io#6]
It would be realy nice to hace the abillity to create a discussion directly on the blog post.

**Comment by Vheissu** [comment]
This is a great idea as I know running my own blog that people sometimes add things into the comments that make the post even better. I'm exploring something to do this.

**Comment by Vheissu** [comment]
Comments have been added @avrahamcool https://aurelia.io/blog/2024/12/19/new-aurelia-website/

**Comment by avrahamcool** [comment]
wow.. that was quick.

Thanks a lot..
that goes to show how the new site was worth it :)
